### ISSUE TITLE
协程环境下睡眠函数不会导致协程阻塞吗?

### ISSUE THREAD

**Issue by jeristiano** [hyperf/retry#1]
https://github.com/hyperf/retry/blob/c05d2a7c05fff962874a7e4f67ee1fbde2c3b474/src/FlatStrategy.php#L29
请问下,这行代码在协程环境下不会导致协程阻塞吗?

**Comment by limingxinleo** [comment]
肯定会阻塞当前协程。。。但这里就是为了这个效果

不会阻塞进程的
